# Stage 1: Build Stage
FROM golang:1.25-alpine AS builder

# Set working directory inside container
WORKDIR /app

# Copy go mod files
COPY go.mod ./

# Download dependencies
RUN go mod download

# Copy source Code
COPY . .

# Build the binary 
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .

# Stage 2: Runtime stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy only the binary from builder
COPY --from=builder /app/main .


# Expose port
EXPOSE 8080

# Run the application
CMD ["./main"]